# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ankr
from ankr.api.early_access_api import EarlyAccessApi  # noqa: E501
from ankr.rest import ApiException


class TestEarlyAccessApi(unittest.TestCase):
    """EarlyAccessApi unit test stubs"""

    def setUp(self):
        self.api = EarlyAccessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ankr_get_account_balance_historical_post(self):
        """Test case for ankr_get_account_balance_historical_post

        ankr_getAccountBalanceHistorical  # noqa: E501
        """
        pass

    def test_ankr_get_internal_transactions_by_block_number_post(self):
        """Test case for ankr_get_internal_transactions_by_block_number_post

        ankr_getInternalTransactionsByBlockNumber  # noqa: E501
        """
        pass

    def test_ankr_get_internal_transactions_by_parent_hash_post(self):
        """Test case for ankr_get_internal_transactions_by_parent_hash_post

        ankr_getInternalTransactionsByParentHash  # noqa: E501
        """
        pass

    def test_ankr_get_token_price_history_post(self):
        """Test case for ankr_get_token_price_history_post

        ankr_getTokenPriceHistory  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
