# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ankr
from ankr.api.nft_api_api import NFTAPIApi  # noqa: E501
from ankr.rest import ApiException


class TestNFTAPIApi(unittest.TestCase):
    """NFTAPIApi unit test stubs"""

    def setUp(self):
        self.api = NFTAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ankr_get_nft_holders_post(self):
        """Test case for ankr_get_nft_holders_post

        ankr_getNFTHolders  # noqa: E501
        """
        pass

    def test_ankr_get_nft_metadata_post(self):
        """Test case for ankr_get_nft_metadata_post

        ankr_getNFTMetadata  # noqa: E501
        """
        pass

    def test_ankr_get_nft_transfers_post(self):
        """Test case for ankr_get_nft_transfers_post

        ankr_getNftTransfers  # noqa: E501
        """
        pass

    def test_ankr_get_nfts_by_owner_post(self):
        """Test case for ankr_get_nfts_by_owner_post

        ankr_getNFTsByOwner  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
