# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ankr
from ankr.api.query_api_api import QueryAPIApi  # noqa: E501
from ankr.rest import ApiException


class TestQueryAPIApi(unittest.TestCase):
    """QueryAPIApi unit test stubs"""

    def setUp(self):
        self.api = QueryAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ankr_get_blockchain_stats_post(self):
        """Test case for ankr_get_blockchain_stats_post

        ankr_getBlockchainStats  # noqa: E501
        """
        pass

    def test_ankr_get_blocks_post(self):
        """Test case for ankr_get_blocks_post

        ankr_getBlocks  # noqa: E501
        """
        pass

    def test_ankr_get_interactions_post(self):
        """Test case for ankr_get_interactions_post

        ankr_getInteractions  # noqa: E501
        """
        pass

    def test_ankr_get_logs_post(self):
        """Test case for ankr_get_logs_post

        ankr_getLogs  # noqa: E501
        """
        pass

    def test_ankr_get_token_transfers_post(self):
        """Test case for ankr_get_token_transfers_post

        ankr_getTokenTransfers  # noqa: E501
        """
        pass

    def test_ankr_get_transactions_by_address_post(self):
        """Test case for ankr_get_transactions_by_address_post

        ankr_getTransactionsByAddress  # noqa: E501
        """
        pass

    def test_ankr_get_transactions_by_hash_post(self):
        """Test case for ankr_get_transactions_by_hash_post

        ankr_getTransactionsByHash  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
