# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ankr
from ankr.models.ankr_get_internal_transactions_by_parent_hash_body import AnkrGetInternalTransactionsByParentHashBody  # noqa: E501
from ankr.rest import ApiException


class TestAnkrGetInternalTransactionsByParentHashBody(unittest.TestCase):
    """AnkrGetInternalTransactionsByParentHashBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnkrGetInternalTransactionsByParentHashBody(self):
        """Test AnkrGetInternalTransactionsByParentHashBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ankr.models.ankr_get_internal_transactions_by_parent_hash_body.AnkrGetInternalTransactionsByParentHashBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
