# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import ankr
from ankr.api.token_api_api import TokenAPIApi  # noqa: E501
from ankr.rest import ApiException


class TestTokenAPIApi(unittest.TestCase):
    """TokenAPIApi unit test stubs"""

    def setUp(self):
        self.api = TokenAPIApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_ankr_explain_token_price_post(self):
        """Test case for ankr_explain_token_price_post

        ankr_explainTokenPrice  # noqa: E501
        """
        pass

    def test_ankr_get_account_balance_post(self):
        """Test case for ankr_get_account_balance_post

        ankr_getAccountBalance  # noqa: E501
        """
        pass

    def test_ankr_get_currencies_post(self):
        """Test case for ankr_get_currencies_post

        ankr_getCurrencies  # noqa: E501
        """
        pass

    def test_ankr_get_token_holders_count_post(self):
        """Test case for ankr_get_token_holders_count_post

        ankr_getTokenHoldersCount  # noqa: E501
        """
        pass

    def test_ankr_get_token_holders_post(self):
        """Test case for ankr_get_token_holders_post

        ankr_getTokenHolders  # noqa: E501
        """
        pass

    def test_ankr_get_token_price_post(self):
        """Test case for ankr_get_token_price_post

        ankr_getTokenPrice  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
