# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from ankr_gen.api_client import ApiClient


class EarlyAccessApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def ankr_get_account_balance_historical_post(self, **kwargs):  # noqa: E501
        """ankr_getAccountBalanceHistorical  # noqa: E501

        Retrieves the historical balance of the specified account.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ankr_get_account_balance_historical_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param AnkrGetAccountBalanceHistoricalBody body:
        :return: InlineResponse2002
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ankr_get_account_balance_historical_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.ankr_get_account_balance_historical_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def ankr_get_account_balance_historical_post_with_http_info(self, **kwargs):  # noqa: E501
        """ankr_getAccountBalanceHistorical  # noqa: E501

        Retrieves the historical balance of the specified account.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ankr_get_account_balance_historical_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param AnkrGetAccountBalanceHistoricalBody body:
        :return: InlineResponse2002
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ankr_get_account_balance_historical_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/?ankr_getAccountBalanceHistorical', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2002',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ankr_get_internal_transactions_by_block_number_post(self, **kwargs):  # noqa: E501
        """ankr_getInternalTransactionsByBlockNumber  # noqa: E501

        Retrieves the details of internal transactions for the specified block number. Internal transactions are callbacks that happen during contract-to-contract interactions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ankr_get_internal_transactions_by_block_number_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param AnkrGetInternalTransactionsByBlockNumberBody body:
        :return: InlineResponse2007
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ankr_get_internal_transactions_by_block_number_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.ankr_get_internal_transactions_by_block_number_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def ankr_get_internal_transactions_by_block_number_post_with_http_info(self, **kwargs):  # noqa: E501
        """ankr_getInternalTransactionsByBlockNumber  # noqa: E501

        Retrieves the details of internal transactions for the specified block number. Internal transactions are callbacks that happen during contract-to-contract interactions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ankr_get_internal_transactions_by_block_number_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param AnkrGetInternalTransactionsByBlockNumberBody body:
        :return: InlineResponse2007
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ankr_get_internal_transactions_by_block_number_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/?ankr_getInternalTransactionsByBlockNumber', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2007',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ankr_get_internal_transactions_by_parent_hash_post(self, **kwargs):  # noqa: E501
        """ankr_getInternalTransactionsByParentHash  # noqa: E501

        Retrieves the details of internal transactions for the specified parent transaction hash. Internal transactions are callbacks that happen during contract-to-contract interactions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ankr_get_internal_transactions_by_parent_hash_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param AnkrGetInternalTransactionsByParentHashBody body:
        :return: InlineResponse2007
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ankr_get_internal_transactions_by_parent_hash_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.ankr_get_internal_transactions_by_parent_hash_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def ankr_get_internal_transactions_by_parent_hash_post_with_http_info(self, **kwargs):  # noqa: E501
        """ankr_getInternalTransactionsByParentHash  # noqa: E501

        Retrieves the details of internal transactions for the specified parent transaction hash. Internal transactions are callbacks that happen during contract-to-contract interactions.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ankr_get_internal_transactions_by_parent_hash_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param AnkrGetInternalTransactionsByParentHashBody body:
        :return: InlineResponse2007
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ankr_get_internal_transactions_by_parent_hash_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/?ankr_getInternalTransactionsByParentHash', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse2007',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def ankr_get_token_price_history_post(self, **kwargs):  # noqa: E501
        """ankr_getTokenPriceHistory  # noqa: E501

        Retrieves the historical price of the specified token.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ankr_get_token_price_history_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param AnkrGetTokenPriceHistoryBody body:
        :return: InlineResponse20016
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.ankr_get_token_price_history_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.ankr_get_token_price_history_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def ankr_get_token_price_history_post_with_http_info(self, **kwargs):  # noqa: E501
        """ankr_getTokenPriceHistory  # noqa: E501

        Retrieves the historical price of the specified token.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.ankr_get_token_price_history_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param AnkrGetTokenPriceHistoryBody body:
        :return: InlineResponse20016
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method ankr_get_token_price_history_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/?ankr_getTokenPriceHistory', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='InlineResponse20016',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
