# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnkrGetInternalTransactionsByBlockNumberParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'block_number': 'int',
        'blockchain': 'str',
        'only_with_value': 'bool',
        'sync_check': 'bool'
    }

    attribute_map = {
        'block_number': 'blockNumber',
        'blockchain': 'blockchain',
        'only_with_value': 'onlyWithValue',
        'sync_check': 'syncCheck'
    }

    def __init__(self, block_number=None, blockchain=None, only_with_value=None, sync_check=None):  # noqa: E501
        """AnkrGetInternalTransactionsByBlockNumberParams - a model defined in Swagger"""  # noqa: E501
        self._block_number = None
        self._blockchain = None
        self._only_with_value = None
        self._sync_check = None
        self.discriminator = None
        if block_number is not None:
            self.block_number = block_number
        self.blockchain = blockchain
        if only_with_value is not None:
            self.only_with_value = only_with_value
        if sync_check is not None:
            self.sync_check = sync_check

    @property
    def block_number(self):
        """Gets the block_number of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501

        Number of the block that contains the transaction.  # noqa: E501

        :return: The block_number of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501
        :rtype: int
        """
        return self._block_number

    @block_number.setter
    def block_number(self, block_number):
        """Sets the block_number of this AnkrGetInternalTransactionsByBlockNumberParams.

        Number of the block that contains the transaction.  # noqa: E501

        :param block_number: The block_number of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501
        :type: int
        """

        self._block_number = block_number

    @property
    def blockchain(self):
        """Gets the blockchain of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501

        Name of the blockchain. Acceptable values: arbitrum, avalanche, base, bsc, eth, fantom, flare, gnosis, optimism, polygon, polygon_zkevm, rollux, syscoin, zksync_era, avalanche_fuji, eth_goerli, optimism_testnet, polygon_mumbai.  # noqa: E501

        :return: The blockchain of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501
        :rtype: str
        """
        return self._blockchain

    @blockchain.setter
    def blockchain(self, blockchain):
        """Sets the blockchain of this AnkrGetInternalTransactionsByBlockNumberParams.

        Name of the blockchain. Acceptable values: arbitrum, avalanche, base, bsc, eth, fantom, flare, gnosis, optimism, polygon, polygon_zkevm, rollux, syscoin, zksync_era, avalanche_fuji, eth_goerli, optimism_testnet, polygon_mumbai.  # noqa: E501

        :param blockchain: The blockchain of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501
        :type: str
        """
        if blockchain is None:
            raise ValueError("Invalid value for `blockchain`, must not be `None`")  # noqa: E501
        allowed_values = ["arbitrum", "avalanche", "avalanche_fuji", "base", "bsc", "eth", "eth_goerli", "fantom", "flare", "gnosis", "linea", "optimism", "optimism_testnet", "polygon", "polygon_mumbai", "polygon_zkevm", "rollux", "scroll", "syscoin"]  # noqa: E501
        if blockchain not in allowed_values:
            raise ValueError(
                "Invalid value for `blockchain` ({0}), must be one of {1}"  # noqa: E501
                .format(blockchain, allowed_values)
            )

        self._blockchain = blockchain

    @property
    def only_with_value(self):
        """Gets the only_with_value of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501

        Filtering. Only responses containing the value parameter (true) or all responses (false).  # noqa: E501

        :return: The only_with_value of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501
        :rtype: bool
        """
        return self._only_with_value

    @only_with_value.setter
    def only_with_value(self, only_with_value):
        """Sets the only_with_value of this AnkrGetInternalTransactionsByBlockNumberParams.

        Filtering. Only responses containing the value parameter (true) or all responses (false).  # noqa: E501

        :param only_with_value: The only_with_value of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501
        :type: bool
        """

        self._only_with_value = only_with_value

    @property
    def sync_check(self):
        """Gets the sync_check of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501

        If false, the data is returned regardless of indexer health, if true, the data is returned only when the indexer health check is positive.  # noqa: E501

        :return: The sync_check of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501
        :rtype: bool
        """
        return self._sync_check

    @sync_check.setter
    def sync_check(self, sync_check):
        """Sets the sync_check of this AnkrGetInternalTransactionsByBlockNumberParams.

        If false, the data is returned regardless of indexer health, if true, the data is returned only when the indexer health check is positive.  # noqa: E501

        :param sync_check: The sync_check of this AnkrGetInternalTransactionsByBlockNumberParams.  # noqa: E501
        :type: bool
        """

        self._sync_check = sync_check

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnkrGetInternalTransactionsByBlockNumberParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnkrGetInternalTransactionsByBlockNumberParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
