# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnkrGetInteractionsParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'sync_check': 'bool'
    }

    attribute_map = {
        'address': 'address',
        'sync_check': 'syncCheck'
    }

    def __init__(self, address=None, sync_check=None):  # noqa: E501
        """AnkrGetInteractionsParams - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._sync_check = None
        self.discriminator = None
        self.address = address
        if sync_check is not None:
            self.sync_check = sync_check

    @property
    def address(self):
        """Gets the address of this AnkrGetInteractionsParams.  # noqa: E501

        Address of a wallet or a contract.  # noqa: E501

        :return: The address of this AnkrGetInteractionsParams.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this AnkrGetInteractionsParams.

        Address of a wallet or a contract.  # noqa: E501

        :param address: The address of this AnkrGetInteractionsParams.  # noqa: E501
        :type: str
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def sync_check(self):
        """Gets the sync_check of this AnkrGetInteractionsParams.  # noqa: E501

        If true the info will be returned regardless of the indexer health.  # noqa: E501

        :return: The sync_check of this AnkrGetInteractionsParams.  # noqa: E501
        :rtype: bool
        """
        return self._sync_check

    @sync_check.setter
    def sync_check(self, sync_check):
        """Sets the sync_check of this AnkrGetInteractionsParams.

        If true the info will be returned regardless of the indexer health.  # noqa: E501

        :param sync_check: The sync_check of this AnkrGetInteractionsParams.  # noqa: E501
        :type: bool
        """

        self._sync_check = sync_check

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnkrGetInteractionsParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnkrGetInteractionsParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
