# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnkrGetTransactionsByAddressParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'list[str]',
        'blockchain': 'list[str]',
        'desc_order': 'bool',
        'from_block': 'int',
        'from_timestamp': 'int',
        'include_logs': 'bool',
        'page_size': 'int',
        'page_token': 'str',
        'sync_check': 'bool',
        'to_block': 'object',
        'to_timestamp': 'object'
    }

    attribute_map = {
        'address': 'address',
        'blockchain': 'blockchain',
        'desc_order': 'descOrder',
        'from_block': 'fromBlock',
        'from_timestamp': 'fromTimestamp',
        'include_logs': 'includeLogs',
        'page_size': 'pageSize',
        'page_token': 'pageToken',
        'sync_check': 'syncCheck',
        'to_block': 'toBlock',
        'to_timestamp': 'toTimestamp'
    }

    def __init__(self, address=None, blockchain=None, desc_order=None, from_block=None, from_timestamp=None, include_logs=None, page_size=None, page_token=None, sync_check=None, to_block=None, to_timestamp=None):  # noqa: E501
        """AnkrGetTransactionsByAddressParams - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._blockchain = None
        self._desc_order = None
        self._from_block = None
        self._from_timestamp = None
        self._include_logs = None
        self._page_size = None
        self._page_token = None
        self._sync_check = None
        self._to_block = None
        self._to_timestamp = None
        self.discriminator = None
        self.address = address
        if blockchain is not None:
            self.blockchain = blockchain
        if desc_order is not None:
            self.desc_order = desc_order
        if from_block is not None:
            self.from_block = from_block
        if from_timestamp is not None:
            self.from_timestamp = from_timestamp
        if include_logs is not None:
            self.include_logs = include_logs
        if page_size is not None:
            self.page_size = page_size
        if page_token is not None:
            self.page_token = page_token
        if sync_check is not None:
            self.sync_check = sync_check
        if to_block is not None:
            self.to_block = to_block
        if to_timestamp is not None:
            self.to_timestamp = to_timestamp

    @property
    def address(self):
        """Gets the address of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        Address to query for transactions.  # noqa: E501

        :return: The address of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: list[str]
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this AnkrGetTransactionsByAddressParams.

        Address to query for transactions.  # noqa: E501

        :param address: The address of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: list[str]
        """
        if address is None:
            raise ValueError("Invalid value for `address`, must not be `None`")  # noqa: E501

        self._address = address

    @property
    def blockchain(self):
        """Gets the blockchain of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        Name of the blockchain or list of blockchain names. Single: eth. Multiple: [arbitrum, avalanche, base, bsc, eth, fantom, flare, gnosis, optimism, polygon, polygon_zkevm, rollux, syscoin, zksync_era, avalanche_fuji, eth_goerli, optimism_testnet, polygon_mumbai]. All chains: empty value.  # noqa: E501

        :return: The blockchain of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: list[str]
        """
        return self._blockchain

    @blockchain.setter
    def blockchain(self, blockchain):
        """Sets the blockchain of this AnkrGetTransactionsByAddressParams.

        Name of the blockchain or list of blockchain names. Single: eth. Multiple: [arbitrum, avalanche, base, bsc, eth, fantom, flare, gnosis, optimism, polygon, polygon_zkevm, rollux, syscoin, zksync_era, avalanche_fuji, eth_goerli, optimism_testnet, polygon_mumbai]. All chains: empty value.  # noqa: E501

        :param blockchain: The blockchain of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: list[str]
        """

        self._blockchain = blockchain

    @property
    def desc_order(self):
        """Gets the desc_order of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        Sorting order. Descending (true) or ascending (false).  # noqa: E501

        :return: The desc_order of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: bool
        """
        return self._desc_order

    @desc_order.setter
    def desc_order(self, desc_order):
        """Sets the desc_order of this AnkrGetTransactionsByAddressParams.

        Sorting order. Descending (true) or ascending (false).  # noqa: E501

        :param desc_order: The desc_order of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: bool
        """

        self._desc_order = desc_order

    @property
    def from_block(self):
        """Gets the from_block of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        Number of the first block in a range. Integer or string (number, hex value, 'earliest' or 'latest').  # noqa: E501

        :return: The from_block of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: int
        """
        return self._from_block

    @from_block.setter
    def from_block(self, from_block):
        """Sets the from_block of this AnkrGetTransactionsByAddressParams.

        Number of the first block in a range. Integer or string (number, hex value, 'earliest' or 'latest').  # noqa: E501

        :param from_block: The from_block of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: int
        """

        self._from_block = from_block

    @property
    def from_timestamp(self):
        """Gets the from_timestamp of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        Beginning of a time period. UNIX timestamp.  # noqa: E501

        :return: The from_timestamp of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: int
        """
        return self._from_timestamp

    @from_timestamp.setter
    def from_timestamp(self, from_timestamp):
        """Sets the from_timestamp of this AnkrGetTransactionsByAddressParams.

        Beginning of a time period. UNIX timestamp.  # noqa: E501

        :param from_timestamp: The from_timestamp of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: int
        """

        self._from_timestamp = from_timestamp

    @property
    def include_logs(self):
        """Gets the include_logs of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        Include logs (true) or exclude them (false).  # noqa: E501

        :return: The include_logs of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: bool
        """
        return self._include_logs

    @include_logs.setter
    def include_logs(self, include_logs):
        """Sets the include_logs of this AnkrGetTransactionsByAddressParams.

        Include logs (true) or exclude them (false).  # noqa: E501

        :param include_logs: The include_logs of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: bool
        """

        self._include_logs = include_logs

    @property
    def page_size(self):
        """Gets the page_size of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        Number of entries per page. int32. Max value — 10000, default value — 100.  # noqa: E501

        :return: The page_size of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this AnkrGetTransactionsByAddressParams.

        Number of entries per page. int32. Max value — 10000, default value — 100.  # noqa: E501

        :param page_size: The page_size of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def page_token(self):
        """Gets the page_token of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        Current page token for pagination.  # noqa: E501

        :return: The page_token of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: str
        """
        return self._page_token

    @page_token.setter
    def page_token(self, page_token):
        """Sets the page_token of this AnkrGetTransactionsByAddressParams.

        Current page token for pagination.  # noqa: E501

        :param page_token: The page_token of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: str
        """

        self._page_token = page_token

    @property
    def sync_check(self):
        """Gets the sync_check of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        If false, the data is returned regardless of indexer health, if true, the data is returned only when the indexer health check is positive.  # noqa: E501

        :return: The sync_check of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: bool
        """
        return self._sync_check

    @sync_check.setter
    def sync_check(self, sync_check):
        """Sets the sync_check of this AnkrGetTransactionsByAddressParams.

        If false, the data is returned regardless of indexer health, if true, the data is returned only when the indexer health check is positive.  # noqa: E501

        :param sync_check: The sync_check of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: bool
        """

        self._sync_check = sync_check

    @property
    def to_block(self):
        """Gets the to_block of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        Number of the last block in a range. Integer or string (number, hex value, 'earliest' or 'latest').  # noqa: E501

        :return: The to_block of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: object
        """
        return self._to_block

    @to_block.setter
    def to_block(self, to_block):
        """Sets the to_block of this AnkrGetTransactionsByAddressParams.

        Number of the last block in a range. Integer or string (number, hex value, 'earliest' or 'latest').  # noqa: E501

        :param to_block: The to_block of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: object
        """

        self._to_block = to_block

    @property
    def to_timestamp(self):
        """Gets the to_timestamp of this AnkrGetTransactionsByAddressParams.  # noqa: E501

        End of a time period. UNIX timestamp.  # noqa: E501

        :return: The to_timestamp of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :rtype: object
        """
        return self._to_timestamp

    @to_timestamp.setter
    def to_timestamp(self, to_timestamp):
        """Sets the to_timestamp of this AnkrGetTransactionsByAddressParams.

        End of a time period. UNIX timestamp.  # noqa: E501

        :param to_timestamp: The to_timestamp of this AnkrGetTransactionsByAddressParams.  # noqa: E501
        :type: object
        """

        self._to_timestamp = to_timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnkrGetTransactionsByAddressParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnkrGetTransactionsByAddressParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
