# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnkrGetTokenPriceHistoryParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'blockchain': 'str',
        'contract_address': 'str',
        'from_timestamp': 'int',
        'interval': 'int',
        'limit': 'int',
        'sync_check': 'bool',
        'to_timestamp': 'object'
    }

    attribute_map = {
        'blockchain': 'blockchain',
        'contract_address': 'contractAddress',
        'from_timestamp': 'fromTimestamp',
        'interval': 'interval',
        'limit': 'limit',
        'sync_check': 'syncCheck',
        'to_timestamp': 'toTimestamp'
    }

    def __init__(self, blockchain=None, contract_address=None, from_timestamp=None, interval=None, limit=None, sync_check=None, to_timestamp=None):  # noqa: E501
        """AnkrGetTokenPriceHistoryParams - a model defined in Swagger"""  # noqa: E501
        self._blockchain = None
        self._contract_address = None
        self._from_timestamp = None
        self._interval = None
        self._limit = None
        self._sync_check = None
        self._to_timestamp = None
        self.discriminator = None
        self.blockchain = blockchain
        if contract_address is not None:
            self.contract_address = contract_address
        if from_timestamp is not None:
            self.from_timestamp = from_timestamp
        if interval is not None:
            self.interval = interval
        if limit is not None:
            self.limit = limit
        if sync_check is not None:
            self.sync_check = sync_check
        if to_timestamp is not None:
            self.to_timestamp = to_timestamp

    @property
    def blockchain(self):
        """Gets the blockchain of this AnkrGetTokenPriceHistoryParams.  # noqa: E501

        Name of the blockchain. Acceptable values: arbitrum, avalanche, base, bsc, eth, fantom, flare, gnosis, optimism, polygon, polygon_zkevm, rollux, syscoin, zksync_era, avalanche_fuji, eth_goerli, optimism_testnet, polygon_mumbai.  # noqa: E501

        :return: The blockchain of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :rtype: str
        """
        return self._blockchain

    @blockchain.setter
    def blockchain(self, blockchain):
        """Sets the blockchain of this AnkrGetTokenPriceHistoryParams.

        Name of the blockchain. Acceptable values: arbitrum, avalanche, base, bsc, eth, fantom, flare, gnosis, optimism, polygon, polygon_zkevm, rollux, syscoin, zksync_era, avalanche_fuji, eth_goerli, optimism_testnet, polygon_mumbai.  # noqa: E501

        :param blockchain: The blockchain of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :type: str
        """
        if blockchain is None:
            raise ValueError("Invalid value for `blockchain`, must not be `None`")  # noqa: E501
        allowed_values = ["arbitrum", "avalanche", "avalanche_fuji", "base", "bsc", "eth", "eth_goerli", "fantom", "flare", "gnosis", "linea", "optimism", "optimism_testnet", "polygon", "polygon_mumbai", "polygon_zkevm", "rollux", "scroll", "syscoin"]  # noqa: E501
        if blockchain not in allowed_values:
            raise ValueError(
                "Invalid value for `blockchain` ({0}), must be one of {1}"  # noqa: E501
                .format(blockchain, allowed_values)
            )

        self._blockchain = blockchain

    @property
    def contract_address(self):
        """Gets the contract_address of this AnkrGetTokenPriceHistoryParams.  # noqa: E501

        Address of the token contract.  # noqa: E501

        :return: The contract_address of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :rtype: str
        """
        return self._contract_address

    @contract_address.setter
    def contract_address(self, contract_address):
        """Sets the contract_address of this AnkrGetTokenPriceHistoryParams.

        Address of the token contract.  # noqa: E501

        :param contract_address: The contract_address of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :type: str
        """

        self._contract_address = contract_address

    @property
    def from_timestamp(self):
        """Gets the from_timestamp of this AnkrGetTokenPriceHistoryParams.  # noqa: E501

        Beginning of a time period. UNIX timestamp.  # noqa: E501

        :return: The from_timestamp of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :rtype: int
        """
        return self._from_timestamp

    @from_timestamp.setter
    def from_timestamp(self, from_timestamp):
        """Sets the from_timestamp of this AnkrGetTokenPriceHistoryParams.

        Beginning of a time period. UNIX timestamp.  # noqa: E501

        :param from_timestamp: The from_timestamp of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :type: int
        """

        self._from_timestamp = from_timestamp

    @property
    def interval(self):
        """Gets the interval of this AnkrGetTokenPriceHistoryParams.  # noqa: E501

        Time interval for updating the token price. UNIX timestamp.  # noqa: E501

        :return: The interval of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :rtype: int
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this AnkrGetTokenPriceHistoryParams.

        Time interval for updating the token price. UNIX timestamp.  # noqa: E501

        :param interval: The interval of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :type: int
        """

        self._interval = interval

    @property
    def limit(self):
        """Gets the limit of this AnkrGetTokenPriceHistoryParams.  # noqa: E501

        Amount of records to be returned.  # noqa: E501

        :return: The limit of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this AnkrGetTokenPriceHistoryParams.

        Amount of records to be returned.  # noqa: E501

        :param limit: The limit of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :type: int
        """

        self._limit = limit

    @property
    def sync_check(self):
        """Gets the sync_check of this AnkrGetTokenPriceHistoryParams.  # noqa: E501

        If false, the data is returned regardless of indexer health, if true, the data is returned only when the indexer health check is positive.  # noqa: E501

        :return: The sync_check of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :rtype: bool
        """
        return self._sync_check

    @sync_check.setter
    def sync_check(self, sync_check):
        """Sets the sync_check of this AnkrGetTokenPriceHistoryParams.

        If false, the data is returned regardless of indexer health, if true, the data is returned only when the indexer health check is positive.  # noqa: E501

        :param sync_check: The sync_check of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :type: bool
        """

        self._sync_check = sync_check

    @property
    def to_timestamp(self):
        """Gets the to_timestamp of this AnkrGetTokenPriceHistoryParams.  # noqa: E501

        End of a time period. UNIX timestamp.  # noqa: E501

        :return: The to_timestamp of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :rtype: object
        """
        return self._to_timestamp

    @to_timestamp.setter
    def to_timestamp(self, to_timestamp):
        """Sets the to_timestamp of this AnkrGetTokenPriceHistoryParams.

        End of a time period. UNIX timestamp.  # noqa: E501

        :param to_timestamp: The to_timestamp of this AnkrGetTokenPriceHistoryParams.  # noqa: E501
        :type: object
        """

        self._to_timestamp = to_timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnkrGetTokenPriceHistoryParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnkrGetTokenPriceHistoryParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
