# coding: utf-8

"""
    Ankr Advanced API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AnkrExplainTokenPriceParams(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'block_height': 'int',
        'blockchain': 'str',
        'token_address': 'str'
    }

    attribute_map = {
        'block_height': 'blockHeight',
        'blockchain': 'blockchain',
        'token_address': 'tokenAddress'
    }

    def __init__(self, block_height=None, blockchain=None, token_address=None):  # noqa: E501
        """AnkrExplainTokenPriceParams - a model defined in Swagger"""  # noqa: E501
        self._block_height = None
        self._blockchain = None
        self._token_address = None
        self.discriminator = None
        if block_height is not None:
            self.block_height = block_height
        self.blockchain = blockchain
        if token_address is not None:
            self.token_address = token_address

    @property
    def block_height(self):
        """Gets the block_height of this AnkrExplainTokenPriceParams.  # noqa: E501

        Number of the block.  # noqa: E501

        :return: The block_height of this AnkrExplainTokenPriceParams.  # noqa: E501
        :rtype: int
        """
        return self._block_height

    @block_height.setter
    def block_height(self, block_height):
        """Sets the block_height of this AnkrExplainTokenPriceParams.

        Number of the block.  # noqa: E501

        :param block_height: The block_height of this AnkrExplainTokenPriceParams.  # noqa: E501
        :type: int
        """

        self._block_height = block_height

    @property
    def blockchain(self):
        """Gets the blockchain of this AnkrExplainTokenPriceParams.  # noqa: E501

        Name of the blockchain. Acceptable values: arbitrum, avalanche, base, bsc, eth, fantom, flare, gnosis, optimism, polygon, polygon_zkevm, rollux, syscoin, zksync_era, avalanche_fuji, eth_goerli, optimism_testnet, polygon_mumbai.  # noqa: E501

        :return: The blockchain of this AnkrExplainTokenPriceParams.  # noqa: E501
        :rtype: str
        """
        return self._blockchain

    @blockchain.setter
    def blockchain(self, blockchain):
        """Sets the blockchain of this AnkrExplainTokenPriceParams.

        Name of the blockchain. Acceptable values: arbitrum, avalanche, base, bsc, eth, fantom, flare, gnosis, optimism, polygon, polygon_zkevm, rollux, syscoin, zksync_era, avalanche_fuji, eth_goerli, optimism_testnet, polygon_mumbai.  # noqa: E501

        :param blockchain: The blockchain of this AnkrExplainTokenPriceParams.  # noqa: E501
        :type: str
        """
        if blockchain is None:
            raise ValueError("Invalid value for `blockchain`, must not be `None`")  # noqa: E501
        allowed_values = ["arbitrum", "avalanche", "avalanche_fuji", "base", "bsc", "eth", "eth_goerli", "fantom", "flare", "gnosis", "linea", "optimism", "optimism_testnet", "polygon", "polygon_mumbai", "polygon_zkevm", "rollux", "scroll", "syscoin"]  # noqa: E501
        if blockchain not in allowed_values:
            raise ValueError(
                "Invalid value for `blockchain` ({0}), must be one of {1}"  # noqa: E501
                .format(blockchain, allowed_values)
            )

        self._blockchain = blockchain

    @property
    def token_address(self):
        """Gets the token_address of this AnkrExplainTokenPriceParams.  # noqa: E501

        Address of the token contract.  # noqa: E501

        :return: The token_address of this AnkrExplainTokenPriceParams.  # noqa: E501
        :rtype: str
        """
        return self._token_address

    @token_address.setter
    def token_address(self, token_address):
        """Sets the token_address of this AnkrExplainTokenPriceParams.

        Address of the token contract.  # noqa: E501

        :param token_address: The token_address of this AnkrExplainTokenPriceParams.  # noqa: E501
        :type: str
        """

        self._token_address = token_address

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AnkrExplainTokenPriceParams, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AnkrExplainTokenPriceParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
